name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add package-lock.json
        git commit -m "Update package-lock.json" || echo "No changes to commit"

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test --if-present

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . # The folder the action should deploy
        branch: gh-pages # The branch the action should deploy to
        token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates this secret
        clean: true # Automatically remove deleted files from the deployment
